# Spring properties
spring:
  application:
     name: math-classes-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      leaseRenewalIntervalInSeconds: 30

# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port